Repository semanticarts/gist, pull requests merged in 2020-04, with the labels that each got.

#230 Explicit imports in gistCore. Closes #80
  OntologyFiles/gistCore.owl
Labels: impact: patch

#234 Improve the definition of SimpleUnitOfMeasure (stylistic change only). Fixes #84.
  OntologyFiles/gistTop.owl
Labels: impact: patch

#231 Correct gist:convertToBase value on gist:_minute from 1.0 to 60.0. Fixes #82.
  OntologyFiles/gistTime.owl
  doc/ReleaseNotes.md
Labels: effort: small, impact: patch

#236 First version of ChangeAndReleaseManagement documentation
  doc/ChangeAndReleaseManagement.md
Labels: area: documentation, impact: patch

#235 Initial version of submission guidelines (Contributing.md). Fixes #190.
  docs/Contributing.md
  docs/ReleaseNotes.md
  docs/gistStyleGuide.md
Labels: area: documentation, impact: patch
