Repository semanticarts/gist, pull requests merged in 2020-08, with the labels that each got.

#332 Documentation updates
  docs/.markdownlint.json
  docs/ChangeAndReleaseManagement.md
  docs/Contributing.md
  docs/ReleaseNotes.md
  docs/gistStyleGuide.md
Labels: area: documentation

#345 Replace gist:Weight with gist:Mass - fixes #105
  gistCore.owl
  gistDeprecated.owl
Labels: impact: minor

#346 Add 'Next Release' section
  docs/ReleaseNotes.md
Labels: area: documentation, impact: patch

#347 Add release notes template
  docs/Contributing.md
  docs/ReleaseNotes.md
  docs/ReleaseNotesTemplate.md
Labels: area: documentation, impact: patch

#357 Deprecate gist:_unitedNations
  docs/ReleaseNotes.md
  gistCore.ttl
  gistDeprecated.ttl
Labels: impact: patch
