Repository semanticarts/gist, pull requests merged in 2023-07, with the labels that each got.

#928 Add newline to property format HTML table. Fixes #923
  docs/ReleaseNotes.md
Labels: impact: patch, area: documentation

#920 Fix wrong apostrophe in docs/Namespace.md
  docs/Namespace.md
  docs/release_notes/patch-919-wrong-apostrophe
Labels: type: bug, impact: patch, area: documentation

#927 Add missing owl:Thing assertions
  gistCore.ttl
Labels: impact: patch
